version: 2
jobs:
  test:
    environment:
      - NODE_ENV: test
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - restore_cache:
          key: npm-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: npm-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test
      - build:
          filters:
            branches:
              only: cci
